using System;
using System.Collections.Generic;
using System.Text;
using NetDataAccess.Base.DLL;
using NetDataAccess.Base.Config;
using System.Threading;
using System.Windows.Forms;
using mshtml;
using NetDataAccess.Base.Definition;
using System.IO;
using NetDataAccess.Base.Common;
using NPOI.SS.UserModel;
using NetDataAccess.Base.EnumTypes;
using NetDataAccess.Base.UI;
using Newtonsoft.Json.Linq;
using HtmlAgilityPack;
using NetDataAccess.Base.Writer;
using NetDataAccess.Base.DB;
using NetDataAccess.Base.Reader;

namespace NetDataAccess.Extended.LiShi.LiShiZhiJia
{
    public class GetAllRenWuDetailPages : ExternalRunWebPage
    { 
        public override bool AfterAllGrab(IListSheet listSheet)
        {
            this.GetListPageUrls(listSheet); 
            return true;
        }

        private void GetListPageUrls(IListSheet listSheet)
        {
            ExcelWriter ew = this.CreateWriter();

            List<string> ss = new List<string>();

            for (int i = 0; i < listSheet.RowCount; i++)
            {
                Dictionary<string, string> listRow = listSheet.GetRow(i);
                bool giveUp = "Y".Equals(listRow[SysConfig.GiveUpGrabFieldName]);
                string url = listRow[SysConfig.DetailPageUrlFieldName];
                if (!giveUp)
                {
                    Dictionary<string, string> row = new Dictionary<string, string>();
                    row.Add("url", url);
                    try
                    {
                        HtmlAgilityPack.HtmlDocument htmlDoc = this.RunPage.GetLocalHtmlDocument(listSheet, i);

                        HtmlNodeCollection baseInfoNodes = htmlDoc.DocumentNode.SelectNodes("//div[@class=\"tag-people-info-base\"]/ul/li");
                        for (int j = 0; j < baseInfoNodes.Count; j++)
                        {
                            HtmlNode baseInfoNode = baseInfoNodes[j];
                            HtmlNode nameNode = baseInfoNode.SelectSingleNode("./span[@class=\"tag-people-info-base-t\"]");
                            HtmlNode valueNode = baseInfoNode.SelectSingleNode("./span[@class=\"tag-people-info-base-d\"]");
                            string infoName = CommonUtil.HtmlDecode(nameNode.InnerText).Trim().Replace(" ", "").Replace(":", "");
                            string infoValue = CommonUtil.HtmlDecode(valueNode.InnerText).Trim();
                            try
                            {
                                row.Add(infoName, infoValue);
                            }
                            catch (Exception ex)
                            {
                                throw ex;
                            }
                            if (!ss.Contains(infoName))
                            {
                                ss.Add(infoName);
                            }
                        }

                        HtmlNodeCollection otherInfoNodes = htmlDoc.DocumentNode.SelectNodes("//div[@class=\"tag-people-info-other\"]/ul/li"); 
                        if(otherInfoNodes!=null){
                            for (int j = 0; j < otherInfoNodes.Count; j++)
                            {
                                HtmlNode otherInfoNode = otherInfoNodes[j];
                                HtmlNode nameNode = otherInfoNode.SelectSingleNode("./span[@class=\"tag-people-info-other-t\"]");
                                HtmlNode valueNode = otherInfoNode.SelectSingleNode("./span[@class=\"tag-people-info-other-d\"]");
                                string infoName = CommonUtil.HtmlDecode(nameNode.InnerText).Trim().Replace(" ", "").Replace(":", "");
                                string infoValue = CommonUtil.HtmlDecode(valueNode.InnerText).Trim();
                                try
                                {
                                    if (row.ContainsKey(infoName))
                                    {
                                        if (infoValue != row[infoName])
                                        {
                                            infoValue = row[infoName] + " " + infoValue;
                                            row[infoName] = infoValue;
                                        }
                                    }
                                    else
                                    {
                                        row.Add(infoName, infoValue);
                                    }
                                }
                                catch (Exception ex)
                                {
                                    throw ex;
                                }
                                if (!ss.Contains(infoName))
                                {
                                    ss.Add(infoName);
                                }
                            }
                        }

                        HtmlNode descriptionNode = htmlDoc.DocumentNode.SelectSingleNode("//div[@class=\"tag-desc\"]");
                        string description = CommonUtil.HtmlDecode(descriptionNode.InnerText).Trim();
                        row.Add("描述", description);

                        ew.AddRow(row);
                    }
                    catch (Exception ex)
                    { 
                        throw ex;
                    }
                }
            }

            //构造列名
            string sss = CommonUtil.StringArrayToString(ss.ToArray(), "\",\r\n\"");

            ew.SaveToDisk();
        }

        private ExcelWriter CreateWriter()
        {
            String exportDir = this.RunPage.GetExportDir(); 
            string resultFilePath = Path.Combine(exportDir, "历史_历史之家_人物详情页.xlsx");

            Dictionary<string, int> resultColumnDic = CommonUtil.InitStringIndexDic(new string[]{
            "url", 
            "姓名",
            "别名",
            "性别",
            "国籍",
            "朝代",
            "出生地",
            "出生日期",
            "逝世日期",
            "职业",
            "官职",
            "地位",
            "追尊",
            "所在时代",
            "主要成就",
            "爵位",
            "庙号",
            "谥号",
            "陵墓",
            "民族",
            "毕业院校",
            "信仰",
            "民族族群",
            "在位",
            "陵寝",
            "登场作品",
            "居所名号",
            "情榜考语",
            "主要作品",
            "绰号",
            "自谦",
            "御赐道号",
            "在位时间",
            "年号",
            "身份职位",
            "葬地",
            "代表作品",
            "历史事件",
            "葬处",
            "后世地位",
            "贡献方向",
            "丈夫",
            "老师",
            "学派",
            "主张",
            "追赠",
            "注音",
            "即位地点",
            "即位年龄",
            "配偶",
            "封爵",
            "笔名",
            "职位",
            "派系",
            "出场作品",
            "字号",
            "称号",
            "行宫",
            "国号",
            "建立政权",
            "继承人",
            "父母",
            "家族成员",
            "军衔",
            "政治面貌",
            "血型",
            "政党",
            "作品",
            "母亲",
            "逝世地",
            "原名",
            "籍贯",
            "妻子",
            "子女",
            "所属势力",
            "祠庙",
            "墓葬",
            "别称",
            "党派",
            "终年岁数",
            "结局",
            "王爵",
            "继任",
            "享年",
            "生父",
            "嗣父",
            "典故",
            "史书记载",
            "封国称王",
            "身份",
            "职务",
            "字",
            "旗籍",
            "身高",
            "性格",
            "重要事件",
            "相关典故",
            "主要战役",
            "梁山排名",
            "所处时代",
            "星号",
            "道号",
            "尊号",
            "汗号",
            "服役军队",
            "参与战役",
            "特征",
            "封号",
            "擅长武术",
            "相关事件",
            "官至",
            "原籍",
            "墓址",
            "逝世地点",
            "人物典故",
            "父亲",
            "位分",
            "祖籍",
            "饰演",
            "配音",
            "排行",
            "女儿",
            "妹妹",
            "在位年数",
            "著名战役",
            "书法作品",
            "所属诗派",
            "官位",
            "擅长",
            "主要事件",
            "位分变化",
            "追废",
            "皇后",
            "主要大臣",
            "重要武臣",
            "兄弟",
            "逝地",
            "追封",
            "出处",
            "年龄",
            "主要武功",
            "武器",
            "爱慕者",
            "成就",
            "星座",
            "梁山座次",
            "弟弟",
            "登场回目",
            "上山前身份",
            "梁山位次",
            "对应星号",
            "梁山职司",
            "出身",
            "所用兵器",
            "政治体制",
            "国家领袖",
            "国土面积",
            "邻国",
            "门派",
            "相关成语",
            "阵亡战役",
            "自号",
            "子",
            "特长",
            "外号",
            "相关故事",
            "名族族群",
            "封地",
            "著名典故",
            "效力国家",
            "号",
            "前任",
            "主要贡献",
            "社会评价",
            "个人荣誉",
            "夫君",
            "姐姐",
            "病史",
            "儿子",
            "祖籍地",
            "儿女",
            "师傅",
            "葬于",
            "墓寝",
            "妻妾",
            "官阶",
            "人品",
            "情人",
            "本经",
            "来源",
            "地区",
            "相关城市",
            "相关小说",
            "相关文物",
            "别号",
            "年号正统",
            "年号天顺",
            "身份变化",
            "容貌",
            "尊称",
            "谱名",
            "服役时间",
            "形象",
            "安葬地",
            "师承",
            "同门",
            "祖先",
            "其他",
            "墓地",
            "荣誉美称",
            "曾任官职",
            "死对头",
            "在位年份",
            "师从",
            "死因",
            "死亡年龄",
            "封爵官职",
            "事件",
            "性格特点",
            "人物评价",
            "语言",
            "姓氏",
            "出生时间",
            "去世时间",
            "满族",
            "获得荣誉",
            "谥",
            "英文名",
            "勋章",
            "同母兄弟",
            "同母姐妹",
            "去世地",
            "墓葬地",
            "哥哥",
            "居住地",
            "在位年号",
            "特点",
            "人物出处",
            "形象出处",
            "教育思想",
            "倡导",
            "正式军衔",
            "战时军衔",
            "最高职务",
            "后代名人",
            "总资产",
            "民间传说",
            "相关战役",
            "荣誉",
            "后人尊称",
            "爱徒",
            "干儿子",
            "上一任",
            "古迹",
            "人生转折",
            "神话体系",
            "所属",
            "居所",
            "司掌",
            "兄弟姐妹",
            "弟子",
            "兵器",
            "星宿",
            "母后",
            "座驾",
            "研究方向",
            "归纳",
            "前夫",
            "第二任丈夫",
            "公益事业",
            "名句",
            "外貌",
            "名族",
            "驸马",
            "情夫",
            "后世追封",
            "好友",
            "初恋",
            "亲人",
            "未婚夫",
            "人物原型",
            "书中影子",
            "官衔",
            "墓所在地",
            "墓发现于",
            "名言",
            "后世子孙",
            "私谥",
            "五子",
            "所属党派",
            "建元",
            "生日",
            "排名",
            "园内居所",
            "前世",
            "花名签",
            "品性",
            "性格特征",
            "文学主张",
            "长子",
            "埋葬地",
            "家庭成员",
            "学历",
            "爱好",
            "人物来源",
            "所任职务",
            "相关作品",
            "知己",
            "经纪公司",
            "墓冢",
            "随笔集",
            "后世尊称",
            "荣誉称号",
            "最高军衔",
            "参加战争",
            "追谥",
            "胞妹",
            "师兄弟",
            "结拜兄弟",
            "技能",
            "皇陵",
            "明朝官职",
            "清朝官职",
            "相貌",
            "力量",
            "坐骑",
            "武功",
            "传人",
            "墓祠",
            "主要事迹",
            "评价",
            "宗教信仰",
            "历史评价",
            "最高荣誉",
            "对应星位",
            "梁山职位",
            "惯用兵器",
            "爱人",
            "发源地",
            "后任",
            "资产",
            "人物关系",
            "品质",
            "原有身份",
            "仇人",
            "所处年代",
            "义弟",
            "毕业学校",
            "本姓",
            "夫人",
            "排位",
            "位阶",
            "赵奢墓",
            "记载",
            "座次",
            "星位",
            "毛遂墓",
            "主人",
            "影视作品",
            "时代",
            "相关人物",
            "外孙",
            "孙子",
            "相关传说",
            "前任君主",
            "后人君主",
            "后任君主",
            "同母姐姐",
            "人物特点",
            "历史记载",
            "学位",
            "外文名",
            "才艺",
            "寝宫",
            "典籍",
            "姐妹",
            "晋升顺序",
            "称呼",
            "后裔",
            "知名弟子",
            "研究范围",
            "侄女",
            "贴身侍女",
            "婚年",
            "徒弟",
            "功夫派系",
            "荫封",
            "官爵",
            "终年",
            "子嗣",
            "纪念地",
            "名誉",
            "后世加封",
            "所任官职",
            "主要传授",
            "种姓",
            "成语典故",
            "义女",
            "主要战事",
            "时期",
            "军职",
            "获得勋章",
            "历任官职",
            "绝技",
            "祠堂",
            "恩师",
            "产生",
            "朋友",
            "主要职位",
            "出生",
            "追贬",
            "主要表现",
            "孩子",
            "说明",
            "原姓",
            "乳名",
            "子孙后代",
            "原型",
            "斋号",
            "遗址地址",
            "人物结局",
            "电影作品",
            "入党时间",
            "帮派",
            "义兄",
            "为商信条",
            "活动时期",
            "故事",
            "记载书籍",
            "警示",
            "采邑",
            "所属作品",
            "故城",
            "城市",
            "夺位",
            "图腾",
            "类别",
            "象征",
            "本质",
            "神职",
            "活动地域",
            "神力",
            "历史典故",
            "后人称谓",
            "汤沐邑",
            "诞辰",
            "兵器坐骑",
            "最终职务",
            "生肖",
            "陵号",
            "流派",
            "重大罪过",
            "死亡目的",
            "搭档",
            "部落标记",
            "祭祀",
            "臣属",
            "諡号",
            "祖父",
            "称谓",
            "作品风格",
            "派别",
            "诗风",
            "伴侣",
            "久居地",
            "修行法门",
            "修炼地",
            "法器",
            "喜好",
            "出家",
            "在位时期",
            "在位时长",
            "出家因缘",
            "法名",
            "所属寺院",
            "养子",
            "涉及战役",
            "内功",
            "招式",
            "仰慕者",
            "尊奉",
            "入伍时间",
            "前任国君",
            "继任国君",
            "年号1",
            "年号2",
            "仓颉遗迹",
            "饰演者",
            "经典台词",
            "逝世年龄",
            "外祖父",
            "性质",
            "传说",
            "关键点",
            "坟墓",
            "相关资料",
            "习练武功",
            "所属流派",
            "主要成绩",
            "文献记载",
            "兄",
            "评语",
            "道场",
            "师兄",
            "法宝",
            "师祖",
            "师父",
            "体貌特征",
            "著名弟子",
            "再传弟子",
            "主公",
            "参军时间",
            "堂兄",
            "墓地位置",
            "使用武器",
            "阵营",
            "人物背景",
            "宠物",
            "祭祀场所",
            "绝学",
            "习惯",
            "轻功",
            "死于",
            "师传",
            "剑法",
            "师弟",
            "表妹",
            "武功特色",
            "提及作品",
            "后人",
            "剑法风格",
            "最强对手",
            "最好朋友",
            "武功绝技",
            "身世",
            "归宿",
            "喜欢的人",
            "忘年之交",
            "死后",
            "职衔",
            "职责",
            "出自",
            "亲属",
            "人物性格",
            "主子",
            "修为",
            "主要法宝",
            "表现力",
            "护教阵法",
            "婆婆",
            "祖母",
            "外遇",
            "属性",
            "作品收藏",
            "侄子",
            "相传人物",
            "主要内容",
            "污点",
            "优点",
            "养父",
            "曾用兵器",
            "門派",
            "恋人",
            "世仇",
            "上司",
            "级别",
            "武功绝学",
            "红颜知己",
            "心上人",
            "暗器",
            "徒孙",
            "描述"
            });

            ExcelWriter resultEW = new ExcelWriter(resultFilePath, "List", resultColumnDic, null);
            return resultEW;
        }
         
    }
}